### ISSUE TITLE
Debugging - teeny crash-reboot loop

### ISSUE THREAD

**Issue by Quothd** [chvmp/firmware#2]
I have come back to the project after a 2 year hiatus. The firmware build (already on the Teensy) ran with no problems but when I tried to re-upload it (as a test before making some revisions) it compiles and uploads successfully but then puts the teensy into a reboot loop.

I am trying to eliminate possible causes but not getting very far. So far I believe problems begin in constructors.h(166) champ::Interfaces::ROSSerial ros_interface;
If I // these 3 lines then the compiled code uploads without causing the teensy to reboot.

Is there a specific type / version of compiler needed or advise in troubleshooting further please as I am stuck.

**Comment by Quothd** [comment]
No response after 6 months

**Comment by WolfwithSword** [comment]
@Quothd  not to necro an old issue, but did you ever find a fix for this? Running into the same problem, but only if I define using Servo Actuators instead of Simulated Actuators from my hardware config. Having a hell of a time trying to debug the crash loop.

**Comment by Quothd** [comment]
Yes I did in the end. It was the ros implementation on the teensy that caused it. I have stripped back ros to the minimum and heavily modified the code to use threads so that I don't have timeouts waiting for other code to run (eg homing)

**Comment by WolfwithSword** [comment]
Ah I was afraid it'd be something to that degree. Got any pointers for the modifications? Or if you're able to share it that'd be great. Been dealing with this crash loop for a long while now and got so close!

**Comment by billynugrahas** [comment]
Hi @Quothd, was wondering if you are able to make it work? you have any hint what needs to be modified?

**Comment by WolfwithSword** [comment]
I know this issue has no response, and @Quothd  hasn't supplied their workaround, but it seems to me like this means the teensy4.0 build of the firmware has a known flaw and would otherwise be deemed unsupported at the time until this issue is resolved.

**Comment by billynugrahas** [comment]
I found the root cause, the servo_.attach must be called inside void setup().
So I removed it from the constructor.
and write a new function:
```
  void begin(int hardware_pin) {
    servo_.attach(hardware_pin);
  }
```
and call begin for each actuato inside the void setup(), like this:

```
void setup() {
  // Call begin() for each actuator
  lfh_actuator.begin(LFH_PIN);
  lfu_actuator.begin(LFU_PIN);
... so on...
```
